easy_admin:
    entities:
        BDS:
            class: App\Entity\BDSContent
            label: 'Divers'
        Sports:
            class: App\Entity\Sport
            label: "Sports de l'école"
        User:
            class: App\Entity\User

    site_name: 'Administration du site IMT Campus'
    design:
        brand_color: 'rgba(0,184,210,1)'
        menu:
            - { label: 'Gestion des bureaux' }
#            - label: 'BDE'
#              children: ['YourEntity']
            - label: 'BDS'
              children: ['Sports', 'BDS']
#            - label: 'BDA'
#              children: ['YourEntity']
            - { label: 'Administration' }
            - User

    user:
        display_name: true
        display_avatar: true
        name_property_path: 'email'