easy_admin:
    entities:
        BDS:
            class: App\Entity\Content
            label: 'Divers'
        Sports:
            class: App\Entity\Sport
            label: "Sports de l'école"
            list:
                fields: ['name','sameLineSport','leaders']
        SportPlanning:
            class: App\Entity\SportPlanning
            label: "Planning des sports"
        Sections:
            class: App\Entity\Section
            label: "Bureaux"
        Member:
            class: App\Entity\Member
            label: "Membres"
        Poles:
            class: App\Entity\Pole
            label: "Poles"
        User:
            class: App\Entity\User

    site_name: 'Administration du site IMT Campus'
    design:
        brand_color: 'rgba(0,184,210,1)'
        menu:
            - { label: 'Gestion des bureaux' }
#            - label: 'BDE'
#              children: ['YourEntity']
            - label: 'BDS'
              children: ['Sports', 'SportPlanning', 'BDS']
#            - label: 'BDA'
#              children: ['YourEntity']
            - Sections
            - Poles
            - Member
            - { label: 'Administration' }
            - User

    user:
        display_name: true
        display_avatar: true
        name_property_path: 'email'