easy_admin:
    entities:
        Content:
            class: App\Entity\Content
            label: "Divers"
            list:
                fields:
                    - { property: 'contentKey' }
                    - { property: 'section' }
                    - { property: 'contentFr' }
        Sports:
            class: App\Entity\Sport
            label: "Sports de l'école"
        Pages:
            class: App\Entity\Page
            label: "Pages dynamiques"
        Images:
            class: App\Entity\Image
            label: "Images du site"
            list:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.images%' }
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
        AuditLogs:
            class: DataDog\AuditBundle\Entity\AuditLog
            label: "AuditLogs"
            disabled_actions: ['new']
            show:
                actions: ['-delete','-edit']
                fields:
                    - { property: 'source' }
                    - { property: 'action' }
                    - { property: 'tbl' }
                    - { property: 'diff', type: 'text' }
            list:
                actions: ['search','-delete','-edit','show']
                fields:
                    - { property: 'source' }
                    - { property: 'action' }
                    - { property: 'tbl' }
                    - { property: 'diff' }
        AuditAssociations:
            class: DataDog\AuditBundle\Entity\Association
            label: "AuditAssociations"
            disabled_actions: ['new']
            show:
                actions: ['-delete','-edit']
            list:
                actions: ['search','-delete','-edit','show']
        Clubs:
            class: App\Entity\Club
            label: "Clubs de l'école"
        SportPlanning:
            class: App\Entity\SportPlanning
            label: "Planning des sports"
        SportLocation:
            class: App\Entity\SportLocation
            label: "Lieux des sports"
        Leader:
            class: App\Entity\Leader
            label: "Responsables"
            list:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.leaders%' }
                    - { property: 'firstName' }
                    - { property: 'lastName' }
            form:
                fields:
                    - { property: 'firstName' }
                    - { property: 'lastName' }
                    - { property: 'imageFile', type: 'vich_image' }
        Sections:
            class: App\Entity\Section
            label: "Bureaux"
        Member:
            class: App\Entity\Member
            label: "Membres des bureaux"
            list:
                fields:
                    - { property: 'firstName' }
                    - { property: 'lastName' }
                    - { property: 'pole' }
                    - { property: 'image',  type: 'image', base_path: '/img/members' }
            form:
                fields:
                    - { property: 'firstName' }
                    - { property: 'lastName' }
                    - { property: 'pole' }
                    - { property: 'imageFile', type: 'vich_image', type_options: { required: false } }
        Poles:
            class: App\Entity\Pole
            label: "Les pôles"
        User:
            class: App\Entity\User
            label: "Utilisateurs"
        Event:
            class: App\Entity\Event
            label: "Événements"
            list:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.events%' }
                    - { property: 'name_fr' }
                    - { property: 'description_fr' }
                    - { property: 'date' }
                    - { property: 'section' }
            form:
                fields:
                    - { property: 'name_fr' }
                    - { property: 'name_en' }
                    - { property: 'description_fr' }
                    - { property: 'description_en' }
                    - { property: 'date' }
                    - { property: 'section' }
                    - { property: 'imageFile', type: 'vich_image', type_options: { required: false } }

        TypeProductBar:
            class: App\Entity\BarProductType
            label: "Catégories de produits"
            form:
                fields:
                    - { property: 'name_en' }
                    - { property: 'name_fr' }
        BarProduct:
            class: App\Entity\BarProduct
            label: "Produits en vente"
            list:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.bar_products%' }
                    - { property: 'name_fr' }
                    - { property: 'price' }
                    - { property: 'type' }
                    - { property: 'isAvailable' }
            show:
                fields:
                    - { property: 'imageFile', type: 'image', base_path: '%app.path.bar_products%' }
            form:
                fields:
                    - { property: 'name_en' }
                    - { property: 'name_fr' }
                    - { property: 'price' }
                    - { property: 'type' }
                    - { property: 'isAvailable' }
                    - { property: 'imageFile', type: 'vich_image', type_options: { required: true } }

    site_name: 'Administration du site IMT Campus Nantes'
    design:
        brand_color: 'rgba(0,184,210,1)'
        menu:
            - { label: 'Gestion des bureaux' }
            - label: 'BDE'
              children: ['BarProduct', 'TypeProductBar']
            - label: 'BDS'
              children: ['Sports', 'SportPlanning' ,'SportLocation']
            - label: 'BDA'
              children: ['Clubs']
            - label: 'Audits'
              children: ['AuditLogs','AuditAssociations']
            - Content
            - Pages
            - Images
            - Leader
            - Event
            - Poles
            - Member
            - { label: 'Administration' }
            - User

    user:
        display_name: true
        display_avatar: true
        name_property_path: 'email'