vich_uploader:
    db_driver: orm

    mappings:
        leaders:
            uri_prefix: '%app.path.leaders%'
            upload_destination: '%kernel.project_dir%/public%app.path.leaders%'
        events:
            uri_prefix: '%app.path.events%'
            upload_destination: '%kernel.project_dir%/public%app.path.events%'
        bar_products:
            uri_prefix: '%app.path.bar_products%'
            upload_destination: '%kernel.project_dir%/public%app.path.bar_products%'
        members:
            uri_prefix: '%app.path.members%'
            upload_destination: '%kernel.project_dir%/public%app.path.members%'
        sponsors:
            uri_prefix: '%app.path.sponsors%'
            upload_destination: '%kernel.project_dir%/public%app.path.sponsors%'
        images:
            uri_prefix: '%app.path.images%'
            upload_destination: '%kernel.project_dir%/public%app.path.images%'
        pe_images:
            uri_prefix: '%app.path.pe_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.pe_image%'
        pe_pdfs:
            uri_prefix: '%app.path.pe_pdfs%'
            upload_destination: '%kernel.project_dir%/public%app.path.pe_pdfs%'