vich_uploader:
    db_driver: orm

    mappings:
        leaders:
            uri_prefix: '%app.path.leaders%'
            upload_destination: '%kernel.project_dir%/public%app.path.leaders%'
        events:
            uri_prefix: '%app.path.events%'
            upload_destination: '%kernel.project_dir%/public%app.path.events%'
        bar_products:
            uri_prefix: '%app.path.bar_products%'
            upload_destination: '%kernel.project_dir%/public%app.path.bar_products%'
        members:
            uri_prefix: '%app.path.members%'
            upload_destination: '%kernel.project_dir%/public%app.path.members%'
        sponsors:
            uri_prefix: '%app.path.sponsors%'
            upload_destination: '%kernel.project_dir%/public%app.path.sponsors%'
