version: '2'
services:
  mysql:
    container_name: flask_mysql
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'imt'
      MYSQL_PASS: 'imt'
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume: